# SPDX-FileCopyrightText: 2025 HungryCuban
# SPDX-FileCopyrightText: 2025 Redrover1760
# SPDX-FileCopyrightText: 2025 core-mene
# SPDX-FileCopyrightText: 2025 starch
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: USSPRifleman
  name: job-name-ussp-rifleman
  description: job-description-ussp-rifleman
  playTimeTracker: JobUSSPRifleman
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 32400 # 9 hrs
  startingGear: USSPRiflemanGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconSecurityCadet" # TODO - new USSP icons
  supervisors: job-supervisors-ussp-sergeant
  canBeAntag: false
  weight: 10
  displayWeight: 10
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, UsspTrackingImplant ]
  - !type:AddComponentSpecial
    components:
    - type: MailDisabled
    - type: SpecialSectorStationRecord
      recordGeneration: FalseRecord
    - type: NpcFactionMember
      factions:
      - USSP
  accessGroups:
  - GeneralAccess
  - USSPLow

- type: startingGear
  id: USSPRiflemanGear
  equipment:
    pocket1: WeaponPistolPollock
    pocket2: Magazine9x19mmPistolFMJ
  storage:
    back:
    - WeaponRifleAK502
    - RadioHandheldNF
