# SPDX-FileCopyrightText: 2025 BlueHNT
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: latheRecipe
  id: PaperCup
  result: PaperCup
  categories: [KitchenNF]
  completetime: 0.4
  applyMaterialDiscount: false
  materials:
    Paper: 50