# SPDX-FileCopyrightText: 2021 Morbo
# SPDX-FileCopyrightText: 2021 Paul Ritter
# SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto
# SPDX-FileCopyrightText: 2022 Morb
# SPDX-FileCopyrightText: 2024 Brandon Hu
# SPDX-FileCopyrightText: 2024 Errant
# SPDX-FileCopyrightText: 2024 Ghagliiarghii
# SPDX-FileCopyrightText: 2024 GreaseMonk
# SPDX-FileCopyrightText: 2024 Ilya246
# SPDX-FileCopyrightText: 2024 Leon Friedrich
# SPDX-FileCopyrightText: 2024 Mr. 27
# SPDX-FileCopyrightText: 2024 Plykiya
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2024 lzk
# SPDX-FileCopyrightText: 2025 Redrover1760
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: false # Frontier: true<false
  objective: roles-antag-syndicate-agent-objective
  # guides: [ Traitors ] # Frontier: removed, irrelevant

- type: antag
  id: TraitorSleeper
  name: roles-antag-syndicate-agent-sleeper-name
  antagonist: true
  setPreference: false # Frontier: true<false
  objective: roles-antag-syndicate-agent-sleeper-objective
  # guides: [ Traitors ] # Frontier: removed, irrelevant

# Syndicate Operative Outfit - Monkey
- type: startingGear
  id: SyndicateOperativeGearMonkey
  equipment:
    head: ClothingHeadHatOutlawHat
    jumpsuit: ClothingUniformJumpsuitOperative
    mask: CigaretteSyndicate

# Syndicate Operative Outfit - Barratry
- type: startingGear
  id: SyndicateOperativeGearExtremelyBasic
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

- type: startingGear
  id: SyndicateOperativeClothing
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackSyndicate
    shoes: ClothingShoesBootsSyndieFilled
    gloves: ClothingHandsGlovesColorBlack

- type: startingGear
  id: SyndicateReinforcementMedic
  parent: SyndicateOperativeClothing
  equipment:
    pocket1: WeaponPistolViper
  inhand:
    - MedkitCombatFilled

- type: startingGear
  id: SyndicateReinforcementSpy
  parent: SyndicateOperativeClothing
  equipment:
    id: AgentIDCard
    mask: ClothingMaskGasVoiceChameleon
    pocket1: WeaponPistolViper

- type: startingGear
  id: SyndicateReinforcementThief
  parent: SyndicateOperativeClothing
  equipment:
    pocket1: WeaponPistolViper
  inhand:
    - ToolboxSyndicateFilled
  storage:
    back:
    - SyndicateJawsOfLife

#Syndicate Operative Outfit - Basic
- type: startingGear
  id: SyndicateOperativeGearBasic
  parent: SyndicateOperativeGearExtremelyBasic
  equipment:
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    pocket1: BaseUplinkRadio200TC # Mono
    id: SyndiPDA
