# SPDX-FileCopyrightText: 2025 Whatstone
# SPDX-FileCopyrightText: 2025 deltanedas
# SPDX-FileCopyrightText: 2025 mikus
#
# SPDX-License-Identifier: AGPL-3.0-or-later

## Static

- type: latheRecipePack
  id: ServiceStatic
  recipes:
  - Bucket
  - DrinkMug
  - DrinkMugMetal
  - DrinkGlass
  - DrinkShotGlass
  - DrinkGlassCoupeShaped
  - CustomDrinkJug
  - FoodPlate
  - FoodPlateSmall
  - FoodPlatePlastic
  - FoodPlateSmallPlastic
  - FoodBowlBig
  - FoodPlateTin
  - FoodPlateMuffinTin
  - FoodKebabSkewer
  - SprayBottle
  - MopItem
  - Holoprojector
  - WetFloorSign

- type: latheRecipePack
  id: ServiceBoardsStatic
  recipes:
  # - BiogeneratorMachineCircuitboard # Frontier: dynamic
  - UniformPrinterMachineCircuitboard
  # - MicrowaveMachineCircuitboard # Frontier: dynamic
  # - ReagentGrinderMachineCircuitboard # Frontier: dynamic
  # - ElectricGrillMachineCircuitboard # Frontier: dynamic
  # - BoozeDispenserMachineCircuitboard # Frontier: dynamic
  # - SodaDispenserMachineCircuitboard # Frontier: dynamic

## Dynamic

- type: latheRecipePack
  id: Janitor
  recipes:
  - AdvMopItem
  - WeaponSprayNozzle
  - ClothingBackpackWaterTank
  - MegaSprayBottle

- type: latheRecipePack
  id: Instruments
  recipes:
  - SynthesizerInstrument

- type: latheRecipePack
  id: ServiceBoards
  recipes:
  - BiofabricatorMachineCircuitboard # Mono
  - FatExtractorMachineCircuitboard
  - HydroponicsTrayMachineCircuitboard # roundstart gear being unlocked roundstart when
  - SeedExtractorMachineCircuitboard # ^
  - MassMediaCircuitboard
  - ReagentGrinderIndustrialMachineCircuitboard
  - JukeboxCircuitBoard
  - DawInstrumentMachineCircuitboard
